# version: '3'

# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#       # command: gunicorn arayeshchi.wsgi
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend
#     depends_on:
#       - mysql
#     links:
#       - mysql

#     # frontend:
#     #   build:
#     #     context: ./frontend
#     #   volumes:
#     #     - ./build
#     #   ports:
#     #     - "3000:3000"

#   mysql:
#     image: mysql:latest
#     container_name: arayeshchi
#     build:
#       context: .
#       # dockerfile: Dockerfile-mysql
#     volumes:
#       - /var/lib/mysql # Define the 'data' volume
#     restart: always
#     ports:
#       - "3306:3306"
#     env_file:
#       - .env # Reference the .env file  
#       # healthcheck:
#       #   test:
#       #     [
#       #       "CMD",
#       #       "mysql",
#       #       "-h",
#       #       "localhost",
#       #       "-u",
#       #       "root",
#       #       "-p${DB_ROOT_PASSWORD}",
#       #       "-e",
#       #       "SELECT 1"
#       #     ]
#       # timeout: 20s
#       # retries: 10
#       #       # nginx:
#       #       #   image: nginx:latest
#       #       #   build:
#       #       #     context: ./nginx
#       #       #   ports:
#       #       #     - "80:8080"
#       #       #   volumes:
#       #       #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       #       #     - frontend:/frontend
#       #       #     - django
#       #       #     - frontend
#       #       #     - mysql
#       #       #   depends_on:
#       #       #     - backend
#       #       #     - frontend

#       # volumes:
#       #   react-build:
#       #   mysql_data:
version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # dockerfile: Dockerfile
    container_name: backend
    # command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    # restart: always
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8
    container_name: database
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_ROOT_PASSWORD: ''
      # MYSQL_DATABASE: 'arayeshi'
      # MYSQL_USER: 'arash'
      # MYSQL_PASSWORD: '1234'
      # volumes:
      # - ./db_data:/var/lib/mysql
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_PASSWORD}",
          "-e",
          "SELECT 1"
        ]
      timeout: 20s
      retries: 10

# volumes:
#   data:
