# Generated by Django 4.2.5 on 2023-12-28 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_user_is_phoneactive"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_phoneactive",
            new_name="is_emailactive",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state",
        ),
    ]
