# Generated by Django 4.2.5 on 2023-12-30 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_emailactive",
        ),
    ]
