# Generated by Django 4.2.5 on 2023-12-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_remove_user_is_emailactive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
