# Generated by Django 4.2.5 on 2024-01-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_user_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
